using ExcelDna.Integration;
using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;

namespace PythonExcelBridge;

public static class PlotCommands
{
    // Default dimensions for test plots created from the menu or PPlotTest().
    // These control the PNG generated by Python, not necessarily the final display
    // size in Excel if Excel-side insertion code overrides width/height.
    private const int DefaultTestPlotWidth = 1200;
    private const int DefaultTestPlotHeight = 800;

    private const string TestPlotTag = "TestPlot";

    // Python code must be a valid C# string literal first, so inner quotes are escaped.
    // This expression creates a matplotlib figure, draws a simple line plot, sets a title,
    // and returns the current figure object.
    private const string TestPlotCode =
        "(__import__(\"matplotlib.pyplot\").pyplot.figure(figsize=(10, 6)), " +
        "__import__(\"matplotlib.pyplot\").pyplot.plot(range(1,11), range(1,11)), " +
        "__import__(\"matplotlib.pyplot\").pyplot.title(\"PythonExcelBridge Test Plot\"), " +
        "__import__(\"matplotlib.pyplot\").pyplot.gcf())[-1]";

    [ExcelFunction(
        Name = "PPlotTest",
        Description = "Create a simple Python test plot and return the PNG path.",
        Category = "PythonExcelBridge")]
    public static object PPlotTest()
    {
        try
        {
            return PythonBridge.Plot(TestPlotCode, TestPlotTag, DefaultTestPlotWidth, DefaultTestPlotHeight);
        }
        catch (Exception ex)
        {
            return $"Error: {ex.Message}";
        }
    }

    [ExcelCommand(
        MenuName = "PythonExcelBridge",
        MenuText = "Insert Plot From Selected Cell",
        ShortCut = "^+P")]
    public static void InsertPlotFromSelectedCellCommand()
    {
        try
        {
            object result = PythonBridge.InsertPlotFromSelectedCell();
            string message = result?.ToString() ?? string.Empty;

            if (IsErrorMessage(message))
            {
                MessageBox.Show(message, "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            TrySetStatusBar("PythonExcelBridge: plot inserted from selected cell.");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Error: {ex.Message}", "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    [ExcelCommand(
        MenuName = "PythonExcelBridge",
        MenuText = "Create And Insert Test Plot")]
    public static void CreateAndInsertTestPlotCommand()
    {
        try
        {
            object plotResult = PythonBridge.Plot(TestPlotCode, TestPlotTag, DefaultTestPlotWidth, DefaultTestPlotHeight);
            string file = plotResult?.ToString() ?? string.Empty;

            if (string.IsNullOrWhiteSpace(file))
            {
                MessageBox.Show("Error: plot path was blank.", "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            if (IsErrorMessage(file))
            {
                MessageBox.Show(file, "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            object insertResult = PythonBridge.InsertPlotFile(file);
            string insertMessage = insertResult?.ToString() ?? string.Empty;

            if (IsErrorMessage(insertMessage))
            {
                MessageBox.Show(insertMessage, "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            TrySetStatusBar(
                $"PythonExcelBridge: test plot created and inserted ({DefaultTestPlotWidth}x{DefaultTestPlotHeight}).");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Error: {ex.Message}", "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    [ExcelCommand(
        MenuName = "PythonExcelBridge",
        MenuText = "Open Plot Folder")]
    public static void OpenPlotFolderCommand()
    {
        try
        {
            string folder = PythonBridge.GetPlotDirectory();

            if (string.IsNullOrWhiteSpace(folder))
            {
                MessageBox.Show("Error: plot folder path was blank.", "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            Directory.CreateDirectory(folder);

            Process.Start(new ProcessStartInfo
            {
                FileName = "explorer.exe",
                Arguments = $"\"{folder}\"",
                UseShellExecute = true
            });

            TrySetStatusBar("PythonExcelBridge: opened plot folder.");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Error: {ex.Message}", "PythonExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    private static bool IsErrorMessage(string message)
    {
        return !string.IsNullOrWhiteSpace(message) &&
               message.StartsWith("Error:", StringComparison.OrdinalIgnoreCase);
    }

    private static void TrySetStatusBar(string message)
    {
        try
        {
            dynamic app = ExcelDnaUtil.Application;
            app.StatusBar = message;
        }
        catch
        {
            // Ignore status bar failures.
        }
    }
}