using ExcelDna.Integration;
using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;

namespace JuliaExcelBridge;

public static class PlotCommands
{
    // Default dimensions for test plots created from the menu or JPlotTest().
    // These control the PNG generated by Julia, not necessarily the final display
    // size in Excel if Excel-side insertion code overrides width/height.
    private const int DefaultTestPlotWidth = 1200;
    private const int DefaultTestPlotHeight = 800;

    private const string TestPlotTag = "TestPlot";
    private const string TestPlotCode = "plot(1:10, 1:10, main='JuliaExcelBridge Test Plot')";

    [ExcelFunction(
        Name = "JPlotTest",
        Description = "Create a simple Julia test plot and return the PNG path.",
        Category = "JuliaExcelBridge")]
    public static object JPlotTest()
    {
        try
        {
            return JBridge.Plot(TestPlotCode, TestPlotTag, DefaultTestPlotWidth, DefaultTestPlotHeight);
        }
        catch (Exception ex)
        {
            return $"Error: {ex.Message}";
        }
    }

    [ExcelCommand(
        MenuName = "JuliaExcelBridge",
        MenuText = "Insert Plot From Selected Cell",
        ShortCut = "^+P")]
    public static void InsertPlotFromSelectedCellCommand()
    {
        try
        {
            object result = JBridge.InsertPlotFromSelectedCell();
            string message = result?.ToString() ?? string.Empty;

            if (IsErrorMessage(message))
            {
                MessageBox.Show(message, "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            TrySetStatusBar("JuliaExcelBridge: plot inserted from selected cell.");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Error: {ex.Message}", "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    [ExcelCommand(
        MenuName = "JuliaExcelBridge",
        MenuText = "Create And Insert Test Plot")]
    public static void CreateAndInsertTestPlotCommand()
    {
        try
        {
            object plotResult = JBridge.Plot(TestPlotCode, TestPlotTag, DefaultTestPlotWidth, DefaultTestPlotHeight);
            string file = plotResult?.ToString() ?? string.Empty;

            if (string.IsNullOrWhiteSpace(file))
            {
                MessageBox.Show("Error: plot path was blank.", "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            if (IsErrorMessage(file))
            {
                MessageBox.Show(file, "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            object insertResult = JBridge.InsertPlotFile(file);
            string insertMessage = insertResult?.ToString() ?? string.Empty;

            if (IsErrorMessage(insertMessage))
            {
                MessageBox.Show(insertMessage, "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            TrySetStatusBar(
                $"JuliaExcelBridge: test plot created and inserted ({DefaultTestPlotWidth}x{DefaultTestPlotHeight}).");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Error: {ex.Message}", "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    [ExcelCommand(
        MenuName = "JuliaExcelBridge",
        MenuText = "Open Plot Folder")]
    public static void OpenPlotFolderCommand()
    {
        try
        {
            string folder = JBridge.GetPlotDirectory();

            if (string.IsNullOrWhiteSpace(folder))
            {
                MessageBox.Show("Error: plot folder path was blank.", "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            Directory.CreateDirectory(folder);

            Process.Start(new ProcessStartInfo
            {
                FileName = "explorer.exe",
                Arguments = $"\"{folder}\"",
                UseShellExecute = true
            });

            TrySetStatusBar("JuliaExcelBridge: opened plot folder.");
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Error: {ex.Message}", "JuliaExcelBridge", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
    }

    private static bool IsErrorMessage(string message)
    {
        return !string.IsNullOrWhiteSpace(message) &&
               message.StartsWith("Error:", StringComparison.OrdinalIgnoreCase);
    }

    private static void TrySetStatusBar(string message)
    {
        try
        {
            dynamic app = ExcelDnaUtil.Application;
            app.StatusBar = message;
        }
        catch
        {
            // Ignore status bar failures.
        }
    }
}